language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
dist: trusty
codecov: true
sudo: required
services:
  - docker
before_install:
  - echo "**** pulling Docker image"
  - docker pull tkpapp/texlive-julia-minimal
notifications:
  email: false
script:
  - echo "**** running Docker"
  - docker run --env-file travis_docker_env.list -t -a STDOUT -a STDIN -a STDERR -v $PWD:/mnt tkpapp/texlive-julia-minimal /mnt/travis_docker_test_script.sh $TRAVIS_JULIA_VERSION
after_success:
  - echo "**** submitting coverage information"
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
